version: "3"
services:
  restapi:
    container_name: boot-app
    image: tantalor93/boot-app
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    container_name: postgres-server
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb